import "server-only";

/**
 * READING 빈칸 — 검토에서 "이 보기도 빈칸에 맞다"고 판정한 짝(정답 → 그 자리에 또 맞는 낱말). 낱말만 있고 강의 글은 없다.
 * 만든 곳: docs/qa-2026-09-18/scripts/merge-reading-cloze-review.cjs ← reading-cloze-review.json(짝마다 판정 기록).
 * 손으로 고치지 않는다 — check-reading-cloze.cjs 가 기록과 생성기를 견준다.
 * 서버 전용(2026-09-27 유출 규칙): 과정 전체 핵심어 목록이라 브라우저에 보내지 않음 — 강의 쪽이 그 강의 짝만 넘김(readingClozeFitsForLesson.ts).
 */
export const CLOZE_ALSO_FITS_REVIEWED: Readonly<Record<string, readonly string[]>> = {
  "absolute": ["correct", "primary"],
  "abstract": ["formal", "important"],
  "absurd": ["constructive", "important"],
  "accident": ["friend"],
  "accidents": ["families", "permits", "victims"],
  "accomplishment": ["command"],
  "accuracy": ["geometry", "mathematics", "perspective"],
  "accurate": ["groundless"],
  "achieve": ["produce"],
  "achieved": ["developed", "improved"],
  "achievement": ["process"],
  "achievements": ["experience", "volunteers"],
  "acquire": ["develop"],
  "act": ["share"],
  "activation": ["stimulation"],
  "active": ["expressive"],
  "add": ["list"],
  "additional": ["mandatory"],
  "adequate": ["required", "suitable"],
  "adolescents": ["families"],
  "adults": ["parents"],
  "advance": ["priceless"],
  "advances": ["developments", "limits"],
  "advocates": ["officials"],
  "age": ["makers"],
  "agree": ["appear", "disagree"],
  "agricultural": ["efficient"],
  "agriculture": ["farming", "products"],
  "air": ["oxygen"],
  "aisle": ["theater"],
  "allow": ["encourage", "support"],
  "altered": ["accepted"],
  "alternatives": ["options"],
  "anger": ["tensions", "upsets"],
  "angry": ["confused", "frustrated", "mad", "silly"],
  "animals": ["communities"],
  "anxiety": ["fear", "fears", "hypnosis"],
  "appeal": ["artistry", "favor", "players", "speed"],
  "appearance": ["tone"],
  "applied": ["address", "customer", "response", "statistical"],
  "appointments": ["situations"],
  "appreciation": ["gratitude", "happiness", "purpose"],
  "appreciative": ["aware"],
  "approval": ["support"],
  "argument": ["language", "meanings"],
  "art": ["existence"],
  "arts": ["music"],
  "asleep": ["active"],
  "assembly": ["brain", "construction", "memory"],
  "asset": ["sense"],
  "assume": ["confirm"],
  "athletes": ["models", "players"],
  "atmosphere": ["periods"],
  "attended": ["recorded"],
  "attitude": ["zeal"],
  "attitudes": ["lifestyle"],
  "audiences": ["friends"],
  "autograph": ["pencil"],
  "aware": ["appreciative", "informed"],
  "balance": ["environment", "fish", "plant"],
  "behavior": ["complexity", "conduct", "conflicts", "organisms", "sleeping", "species"],
  "belief": ["answer", "proof"],
  "believe": ["accept", "agree", "disagree", "maintain"],
  "belong": ["contribute", "develop"],
  "beyond": ["outside"],
  "birds": ["dogs"],
  "birth": ["sight"],
  "blankets": ["heat"],
  "blessed": ["amazed", "grateful"],
  "blindly": ["gradually"],
  "bodies": ["disease", "healing", "illness"],
  "body": ["breathing", "feet", "heart", "muscles", "stomach", "torso"],
  "book": ["music"],
  "books": ["experience", "hardships"],
  "booming": ["isolated"],
  "boredom": ["loneliness"],
  "boss": ["theater"],
  "brain": ["memory"],
  "breathing": ["feet", "laughter", "stomach"],
  "building": ["bicycle"],
  "caring": ["decent"],
  "cause": ["create"],
  "ceiling": ["mosquito"],
  "certain": ["expressive"],
  "chance": ["opportunity"],
  "change": ["choose"],
  "changes": ["temperature"],
  "changing": ["preserving"],
  "character": ["conscience", "voice"],
  "chatting": ["watching"],
  "child": ["grown-up"],
  "choice": ["example"],
  "choose": ["increase", "prepare"],
  "chronically": ["significantly"],
  "civilizations": ["cultures"],
  "clean": ["solar", "sweet"],
  "clear": ["healthy"],
  "cleverness": ["science"],
  "combat": ["contests"],
  "comforting": ["calm", "peaceful"],
  "common": ["cleaner", "traditional"],
  "communicate": ["share"],
  "communication": ["counsel"],
  "company": ["business", "professor"],
  "compete": ["develop"],
  "competent": ["productive"],
  "competition": ["performance"],
  "competitiveness": ["producers"],
  "completely": ["entirely"],
  "complex": ["consumer-driven", "disciplined", "insecure"],
  "complexity": ["conduct"],
  "composed": ["admirers"],
  "computer": ["language"],
  "computers": ["parts"],
  "conceiving": ["conception"],
  "concerned": ["interrelated"],
  "conclude": ["judge"],
  "cone": ["treat"],
  "confined": ["restricted"],
  "conflicting": ["complex"],
  "confused": ["angry", "mad"],
  "conservation": ["happiness"],
  "consider": ["develop"],
  "considerable": ["international"],
  "considerate": ["moral", "strong"],
  "consideration": ["thoughtfulness"],
  "constant": ["changing"],
  "constantly": ["continually"],
  "constructive": ["important"],
  "consume": ["shop"],
  "consumer-driven": ["complex", "harsh", "improvement", "insecure"],
  "consumers": ["shoppers"],
  "contemporary": ["popular"],
  "contests": ["combat", "competition"],
  "continually": ["constantly"],
  "continued": ["private"],
  "contrasting": ["analytical"],
  "controlled": ["developed"],
  "convictions": ["heart"],
  "cooler": ["shorter"],
  "costly": ["terrible"],
  "countries": ["civilizations", "cultures", "growth", "producers"],
  "country": ["press", "table"],
  "courage": ["heart"],
  "court": ["law", "rights"],
  "courts": ["matters"],
  "courtship": ["country"],
  "cousin": ["wife"],
  "create": ["cause"],
  "created": ["offered"],
  "creates": ["causes"],
  "creativity": ["genius"],
  "creature": ["horse"],
  "criticize": ["explain"],
  "crops": ["products"],
  "crowded": ["expensive"],
  "crucial": ["important"],
  "culture": ["beliefs", "customs", "firms", "languages", "objects", "society", "understanding"],
  "cultures": ["civilizations"],
  "customers": ["profits"],
  "customs": ["beliefs", "languages", "purposes"],
  "damage": ["condition", "illnesses", "wounds"],
  "dammed": ["hurt"],
  "dancing": ["prize"],
  "dangerous": ["bad"],
  "dark": ["different", "violent"],
  "database": ["data"],
  "day-to-day": ["particular"],
  "decayed": ["social"],
  "decent": ["caring", "dependable", "honest", "sincere"],
  "decide": ["develop"],
  "deeper": ["higher"],
  "defense": ["industry"],
  "delicious": ["desirable", "favorite"],
  "deliver": ["bring", "influence", "performed"],
  "demands": ["preserved"],
  "dependable": ["decent", "sincere"],
  "described": ["studied"],
  "desires": ["faction"],
  "despair": ["tensions", "upsets"],
  "determination": ["forgiveness", "mind"],
  "develop": ["acquire", "encouraged", "share"],
  "developed": ["improved", "provided"],
  "developing": ["ignorant", "improving"],
  "development": ["survival"],
  "developments": ["advances"],
  "difference": ["truth"],
  "differences": ["conflicts", "pleasures"],
  "different": ["available", "beautiful", "enormous", "exciting", "furniture", "genuine", "negative", "presented", "regular", "relaxing", "violent", "wonderful"],
  "differentiation": ["change"],
  "direct": ["environmental", "growth", "heavy", "human", "strong", "stronger"],
  "directly": ["immediately"],
  "dirty": ["expensive"],
  "disagree": ["agree"],
  "disappointed": ["visited"],
  "disastrous": ["frightening"],
  "disciplined": ["flexible"],
  "discount": ["price"],
  "discouraged": ["hopeless"],
  "discovered": ["evolved"],
  "disease": ["illness"],
  "disguise": ["texture"],
  "distorted": ["accurate"],
  "dogs": ["birds"],
  "domestic": ["vital"],
  "dramatically": ["especially", "overseas"],
  "dread": ["accept"],
  "dreaming": ["pleasure"],
  "dreams": ["goals", "plans"],
  "dwellers": ["populations"],
  "dying": ["old-fashioned"],
  "early": ["alphabetic", "telegraphic"],
  "earn": ["produce"],
  "easy": ["difficult"],
  "eat": ["diet"],
  "economic": ["industrial"],
  "education": ["computers", "exercise", "functions", "inspiration", "opportunities", "society", "traditions", "training", "values"],
  "effective": ["remarkable"],
  "effort": ["exercise"],
  "elements": ["beliefs", "creations", "objects", "organisms", "purposes", "understanding"],
  "emotion": ["words"],
  "emotions": ["fears", "struggles", "triumphs"],
  "employee": ["hand"],
  "empty-handed": ["unprepared"],
  "energy": ["electricity"],
  "enforced": ["continual"],
  "enormous": ["dark", "violent"],
  "enough": ["clear"],
  "environment": ["balance", "community", "planet", "school", "soil", "traffic"],
  "environmental": ["direct"],
  "equal": ["special"],
  "equipment": ["friend"],
  "error": ["mistakes"],
  "establish": ["offer"],
  "established": ["desirable"],
  "ethical": ["medical", "technological"],
  "examine": ["correct"],
  "excited": ["frightened", "impressed"],
  "executives": ["company"],
  "exercise": ["protect"],
  "existence": ["voices"],
  "expectation": ["evaluation", "impressions"],
  "experience": ["achievements", "activities", "courtesy", "emotions", "hardships", "imagination", "instincts", "poetry", "transformation", "triumphs"],
  "explore": ["travel"],
  "exports": ["agreement", "buyers", "coffee", "crop"],
  "expression": ["appearance"],
  "expressive": ["active", "certain", "connected"],
  "extended": ["important", "inappropriate", "public"],
  "extinct": ["dying"],
  "extra": ["giant"],
  "facing": ["involving"],
  "faction": ["clamor", "desires", "factionalism", "fulfillment", "society"],
  "factionalism": ["clamor", "faction"],
  "factors": ["buyers", "countries", "prices"],
  "fame": ["honor"],
  "family": ["health", "intelligence", "religion"],
  "farms": ["communities"],
  "fathers": ["parents"],
  "fears": ["anxiety", "struggles", "triumphs"],
  "feelings": ["emotions", "friends", "knowledge", "observations"],
  "fictional": ["television"],
  "financial": ["government"],
  "findings": ["changes"],
  "firms": ["culture"],
  "focus": ["comment"],
  "forecasters": ["producers"],
  "foreign": ["different", "popular", "vital"],
  "foreigners": ["students"],
  "foretell": ["reveal"],
  "formal": ["abstract", "important"],
  "formula": ["love"],
  "freedom": ["right"],
  "frequent": ["serious"],
  "friend": ["equipment"],
  "friends": ["friendships", "teenagers"],
  "friendships": ["friends"],
  "frightening": ["disastrous", "so-called"],
  "frustrated": ["angry", "mad"],
  "funds": ["volunteers"],
  "fur": ["eyes", "hide"],
  "future": ["dreams", "goals", "station"],
  "gained": ["received"],
  "genius": ["authority", "breakthroughs", "dogma"],
  "genuine": ["different"],
  "germ": ["disease"],
  "giant": ["extra"],
  "goal": ["wealth"],
  "goals": ["dreams", "plans"],
  "governments": ["citizens", "organizations"],
  "grasp": ["knowledge", "mastery", "memorization", "reach"],
  "grateful": ["amazed", "blessed", "remember"],
  "gratitude": ["appreciation"],
  "graying": ["disheveled"],
  "growing": ["foreign", "popular"],
  "hand-made": ["flexible"],
  "happened": ["remained"],
  "happiness": ["recognition", "success"],
  "happy": ["great", "harmonious", "sad"],
  "hard": ["simple"],
  "hardships": ["injustice", "trouble"],
  "harmonious": ["happy", "social"],
  "harsh": ["consumer-driven", "insecure"],
  "healing": ["disease"],
  "health": ["disease", "education", "family", "humor", "illness", "mind"],
  "healthy": ["clear", "enough", "living"],
  "hearing": ["reading"],
  "heart": ["arts", "excellence"],
  "heartbreaking": ["different", "honest", "moving"],
  "heartfelt": ["grateful", "simple"],
  "hearts": ["families", "understanding"],
  "heating": ["operating", "powering"],
  "hide": ["fur"],
  "high": ["unreachable"],
  "history": ["custom", "dishes", "utensils"],
  "hit": ["believe", "punish"],
  "honest": ["decent", "moral", "moving", "sincere", "sound", "strong"],
  "honor": ["fame"],
  "hopeless": ["discouraged"],
  "horse": ["creature"],
  "hospitals": ["comedians"],
  "hot": ["warm"],
  "household": ["vacation"],
  "hurt": ["wronged"],
  "husband": ["grandparent"],
  "ideas": ["attitudes", "feelings", "interpretation", "lifestyle", "tensions", "upsets"],
  "illness": ["health"],
  "illnesses": ["wounds"],
  "image": ["word"],
  "imaginary": ["interested"],
  "imaginative": ["individual", "positive", "productive"],
  "immediately": ["directly"],
  "important": ["abstract", "constructive", "crucial", "difficult", "formal", "healthy", "particular", "powerful"],
  "importantly": ["particularly"],
  "impressed": ["excited", "frightened"],
  "impressions": ["evaluation"],
  "improve": ["transform"],
  "improved": ["developed"],
  "improving": ["developing"],
  "improvise": ["provide"],
  "inappropriate": ["important", "public", "quiet"],
  "increase": ["change"],
  "increased": ["disastrous", "frightening"],
  "individual": ["society"],
  "indivisible": ["independent"],
  "industry": ["knowledge", "performance"],
  "inferior": ["poor"],
  "informed": ["aware"],
  "injustice": ["hardships"],
  "instincts": ["experience"],
  "insurance": ["coverage"],
  "intelligence": ["family"],
  "intent": ["goal", "hand"],
  "interactions": ["demands"],
  "interest": ["attitude", "belief", "zeal"],
  "international": ["environment", "exporting", "major"],
  "interpret": ["influence"],
  "interpretation": ["performance"],
  "involved": ["included"],
  "irresponsive": ["lonely"],
  "items": ["razors"],
  "job": ["friends"],
  "joy": ["wisdom"],
  "justice": ["happiness"],
  "keep": ["leave"],
  "kind": ["feeling"],
  "knowledge": ["curiosity", "language", "learning", "observations", "principles"],
  "labor": ["supply"],
  "laid": ["hatched"],
  "language": ["example", "experience"],
  "largest": ["leading"],
  "lasted": ["helped"],
  "later": ["regardless"],
  "laughing": ["humorous", "laughter"],
  "laughter": ["breathing", "humor"],
  "laws": ["codes", "paths"],
  "leap": ["calendar"],
  "learn": ["speak"],
  "learned": ["decided"],
  "leave": ["stop"],
  "lecture": ["word"],
  "lesson": ["difference"],
  "letter": ["appreciation"],
  "library": ["collection"],
  "lifestyle": ["attitudes", "ideas"],
  "living": ["healthy", "transportation"],
  "loaf": ["bread"],
  "loneliness": ["boredom"],
  "long": ["intellectual"],
  "longing": ["boredom"],
  "lose": ["sweat"],
  "lot": ["culture", "economy", "society"],
  "lovable": ["adorable"],
  "love": ["compassion", "feeling"],
  "mad": ["angry", "confused", "frustrated"],
  "maintain": ["agree", "believe", "disagree"],
  "mankind": ["joy"],
  "manners": ["conversations"],
  "mastery": ["grasp", "knowledge", "memorization"],
  "mathematics": ["geometry"],
  "matters": ["photographs", "words"],
  "mean": ["regret"],
  "medical": ["psychological", "technological"],
  "mediocre": ["particular"],
  "members": ["leaders"],
  "memorization": ["knowledge"],
  "memory": ["brain", "fact", "sound"],
  "merciful": ["dissatisfied"],
  "mind": ["anxiety", "dermatologist", "hypnosis"],
  "misleading": ["surprising", "valid"],
  "models": ["players"],
  "modern": ["important", "weekly"],
  "moon": ["station"],
  "moral": ["considerate", "honest", "inner"],
  "moving": ["honest"],
  "muscles": ["laughter", "sources", "stomach"],
  "music": ["book", "rhymes"],
  "musicians": ["makers", "scientists"],
  "narrow": ["bring", "green", "modern", "undesirable"],
  "natural": ["domestic", "economic", "industrial", "precious", "spiritual", "wild"],
  "nature": ["death", "environment", "fear"],
  "necessary": ["developing"],
  "negative": ["different", "enormous", "violent"],
  "neighboring": ["available"],
  "newspaper": ["fun"],
  "noise": ["environments"],
  "noisy": ["harmful", "high-volume", "poor", "unpredictable", "wild"],
  "northern": ["superstitious"],
  "notes": ["words"],
  "numberless": ["insistent"],
  "objective": ["analytical"],
  "objects": ["subjects"],
  "occurred": ["happened"],
  "offer": ["establish"],
  "offered": ["selling"],
  "old-fashioned": ["dying", "extinct", "print-oriented"],
  "options": ["alternatives"],
  "original": ["positive", "productive"],
  "other-sex": ["different", "successful"],
  "outside": ["beyond"],
  "oxygen": ["air"],
  "painting": ["art", "seascape"],
  "parental": ["special", "true"],
  "parents": ["families"],
  "particular": ["excellent", "important"],
  "passes": ["travels"],
  "paths": ["codes", "laws"],
  "patient": ["relaxed"],
  "patterns": ["differences"],
  "pendulum": ["precision"],
  "perfected": ["needed"],
  "performance": ["behaviors", "experience", "goals", "industry", "interpretation", "loyalty", "objectives", "productivity", "results", "strategy"],
  "personal": ["private"],
  "photographs": ["courts", "words"],
  "physical": ["preventive", "shared"],
  "piece": ["work"],
  "plans": ["goals"],
  "plants": ["habitats", "species"],
  "players": ["athletes"],
  "pleasure": ["ideas", "relaxation"],
  "poetry": ["prose"],
  "polluted": ["rapid"],
  "poor": ["healthy", "hopeless", "nearsighted", "unpredictable"],
  "popular": ["contemporary"],
  "positive": ["competent", "expected", "original", "yourself"],
  "possibilities": ["alternatives"],
  "power": ["telescope"],
  "practical": ["worthwhile"],
  "precision": ["pendulum", "timekeeping"],
  "prejudiced": ["enforced", "fixed"],
  "prepare": ["develop"],
  "prescient": ["insistent"],
  "preserving": ["changing"],
  "pressure": ["worry"],
  "pressures": ["changes", "stimulation"],
  "preventive": ["physical"],
  "price": ["quantity"],
  "priceless": ["advance"],
  "principle": ["strategy"],
  "principles": ["knowledge", "language", "proof"],
  "private": ["personal", "young"],
  "produce": ["achieve", "develop", "request"],
  "producing": ["putting"],
  "production": ["yields"],
  "productive": ["competent", "original"],
  "productivity": ["performance"],
  "products": ["crops"],
  "professional": ["young"],
  "profits": ["customers"],
  "profound": ["old-fashioned"],
  "proper": ["natural"],
  "prosper": ["achieve", "develop", "produce"],
  "provided": ["developed"],
  "provides": ["moves"],
  "providing": ["improved", "increasing", "understanding"],
  "psychological": ["medical"],
  "published": ["basically"],
  "purpose": ["responsibility"],
  "qualifications": ["circumstances", "success"],
  "qualified": ["specialized", "wonderful"],
  "quantity": ["shipping", "trade"],
  "question": ["dilemma", "guidelines"],
  "quiet": ["low"],
  "raised": ["disappointed"],
  "realize": ["accept"],
  "reason": ["words"],
  "received": ["gained"],
  "recently": ["twice"],
  "recognition": ["success"],
  "recognized": ["emphasized"],
  "recorded": ["published"],
  "regularities": ["law", "rules"],
  "rehearing": ["experience", "interpretation", "performance"],
  "relationships": ["network"],
  "relaxed": ["patient"],
  "relief": ["fear"],
  "religion": ["family"],
  "religious": ["destructive"],
  "remember": ["stop"],
  "remind": ["allow"],
  "replied": ["exclaimed", "stormed"],
  "reports": ["coverage"],
  "reputation": ["light"],
  "required": ["industry"],
  "resourcefulness": ["knowledge", "technology"],
  "responsiveness": ["sensitivity"],
  "restful": ["healthy"],
  "results": ["crises", "fear", "intolerance", "narrow-mindedness", "performance", "success"],
  "retouched": ["important"],
  "reveal": ["foretell"],
  "rhymes": ["music"],
  "rhythms": ["slaves"],
  "right": ["capacity"],
  "rises": ["returns"],
  "rocket": ["animal", "chimpanzee", "spaceship"],
  "rolling": ["selling"],
  "romantic": ["business", "rich"],
  "rousing": ["developing", "improving"],
  "rules": ["goals"],
  "rural": ["overcrowded", "urban"],
  "sad": ["happy"],
  "saint": ["friend"],
  "satisfied": ["dissatisfied"],
  "satisfying": ["active"],
  "scatter": ["spread"],
  "school": ["events", "music", "student"],
  "science": ["competition", "training"],
  "scientific": ["disheveled"],
  "scientists": ["musicians"],
  "securing": ["directing", "engaging"],
  "security": ["happiness"],
  "self-improvement": ["amends"],
  "seller": ["success"],
  "sensible": ["attractive", "durable"],
  "sensitivity": ["responsiveness"],
  "serious": ["expected", "shortage"],
  "severely": ["profoundly"],
  "share": ["develop"],
  "sharing": ["transmitting"],
  "sharp": ["universal"],
  "shop": ["consume"],
  "shorter": ["cooler"],
  "similarities": ["conflicts"],
  "sincere": ["honest", "sound"],
  "situations": ["appointments", "conversations"],
  "skilled": ["auto-making"],
  "slaves": ["origin"],
  "slips": ["tumbles"],
  "slowly": ["slightly"],
  "slurping": ["eating"],
  "social": ["active", "values"],
  "society": ["agreement", "culture", "family", "individual", "school", "truth"],
  "solve": ["allow", "evaluate"],
  "somehow": ["immediately"],
  "soul": ["excellence", "support"],
  "sound": ["caring", "decent", "dependable", "honest", "memory", "sincere"],
  "sources": ["energy", "muscles"],
  "spaceship": ["chimpanzee", "rocket", "scientists"],
  "special": ["equal", "important", "parental", "true"],
  "species": ["habitats"],
  "specific": ["helpless"],
  "spiritual": ["natural"],
  "stand": ["usher"],
  "startled": ["pregnant"],
  "steamed": ["beaten"],
  "stillness": ["beauty", "pleasures"],
  "stimulation": ["touch"],
  "stop": ["leave"],
  "storage": ["junk"],
  "strategy": ["goals", "objectives"],
  "strengthened": ["remained"],
  "strong": ["considerate", "honest"],
  "struggles": ["emotions"],
  "studied": ["described"],
  "success": ["happiness", "promotion", "recognition"],
  "suffering": ["joy", "transformation"],
  "suggest": ["insist"],
  "suggests": ["confirms"],
  "summarize": ["published"],
  "summer": ["fair"],
  "sundials": ["pendulum"],
  "sunny": ["bright", "cooler", "shorter"],
  "superhuman": ["complex"],
  "supervised": ["watched"],
  "support": ["consider", "lead"],
  "supported": ["important", "involved", "meaningful", "positive"],
  "survival": ["development", "performance"],
  "survive": ["achieve"],
  "sweet": ["wild"],
  "swinging": ["going"],
  "systems": ["temperature"],
  "tastes": ["opinion"],
  "teachings": ["volumes"],
  "techniques": ["art", "painting"],
  "technological": ["medical"],
  "technology": ["competition", "knowledge", "resourcefulness", "spaceships"],
  "teenage": ["angry", "confused", "frustrated", "mad"],
  "teenagers": ["students"],
  "teens": ["teenagers"],
  "telegraphic": ["alphabetic", "early"],
  "telescope": ["station"],
  "telescopes": ["light", "spaceships", "technology"],
  "temperate": ["different"],
  "tensions": ["anger", "despair", "feelings", "problems"],
  "terminal": ["advanced", "lethal"],
  "terrible": ["costly", "midnight"],
  "torso": ["body"],
  "touch": ["sight", "stimulation"],
  "trade": ["cash", "quantity"],
  "traditional": ["common", "different", "early", "mathematics"],
  "traditions": ["values"],
  "trained": ["original"],
  "training": ["education", "technology"],
  "transform": ["improve"],
  "transmitting": ["sharing"],
  "travel": ["illness", "travellers"],
  "treated": ["observed"],
  "trick": ["joys", "miracle"],
  "trips": ["flights"],
  "triumphs": ["emotions"],
  "trouble": ["hardships"],
  "truth": ["decision-makers"],
  "trying": ["learn"],
  "tumbles": ["slips"],
  "two-year-old": ["irritated"],
  "unchangeable": ["certain"],
  "uncommon": ["childlike", "depressed"],
  "unfold": ["develop"],
  "unhurried": ["different"],
  "unique": ["different", "emerging", "global"],
  "universe": ["earth"],
  "unpaid": ["social", "unskilled"],
  "unprepared": ["empty-handed"],
  "unreachable": ["high"],
  "unskilled": ["unpaid"],
  "untroubled": ["wise"],
  "upsets": ["anger", "despair", "feelings"],
  "urban": ["overcrowded", "rural"],
  "usher": ["boss"],
  "utensils": ["chopsticks", "dishes", "knives"],
  "value": ["truth"],
  "values": ["expectations", "traditions"],
  "vast": ["lonely"],
  "viewed": ["applied"],
  "violent": ["dark", "enormous"],
  "visited": ["pleased"],
  "waggle": ["honeybee"],
  "watched": ["supervised"],
  "weight": ["milk"],
  "whenever": ["because"],
  "wife": ["grandparent"],
  "wild": ["live", "natural", "precious", "sweet"],
  "wisdom": ["companion", "courtesy", "joy"],
  "wish": ["worry"],
  "wood": ["furniture"],
  "word": ["lecture"],
  "work": ["quality", "writing"],
  "workforce": ["producers"],
  "worthwhile": ["practical"],
  "writer": ["readers", "words"],
  "writing": ["dancing", "poetry", "work"],
  "wronged": ["hurt"],
  "yearbook": ["book"],
  "youngster": ["team"],
  "zeal": ["attitude", "interest"],
  "zones": ["country"],
};
