#!/usr/bin/env node
/**
 * SRCH-01 — runs `scripts/buildSearchIndex.ts` so that `prebuild` can rebuild
 * `public/search-index.json` on every build.
 *
 * WHY THIS EXISTS. The index was generated by hand and committed, and nothing
 * regenerated it when content changed. Restoring the `s19-3` lesson therefore
 * left it unfindable: the index listed 81 STUDENT lessons against 82 real ones,
 * and typing `s19-3` into the site's search returned "검색 결과가 없습니다".
 *
 * WHY A RUNNER AND NOT A REWRITE. The logic stays in the `.ts` file, which is
 * the single source of truth and is also read as text by
 * `docs/qa-2026-09-15/scripts/audit-data.cjs`. Node can strip the types by
 * itself, but not resolve `../src/lib/curriculumPresentation` without an
 * extension, so this transpiles the file and gives it a resolver — the same
 * approach `scripts/buildFreeSpeechKeys.mjs` uses.
 *
 *   node scripts/buildSearchIndex.mjs            # regenerate
 *   node scripts/buildSearchIndex.mjs --check    # exit 1 if the file is stale
 */
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { createRequire } from "node:module";
import { findPaidLeaks } from "./paidLeakCheck.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT_FILE = path.join(ROOT, "public", "search-index.json");
const CHECK = process.argv.includes("--check");

const require = createRequire(import.meta.url);
const ts = require(path.join(ROOT, "node_modules", "typescript"));
const cache = new Map();

/** Resolve a relative/`@/` import to a real file, the way tsconfig does. */
function resolveSpec(spec, fromDir) {
  let base;
  if (spec.startsWith("@/")) base = path.join(ROOT, "src", spec.slice(2));
  else if (spec.startsWith(".")) base = path.join(fromDir, spec);
  else return null;
  for (const candidate of [base, `${base}.ts`, `${base}.tsx`, path.join(base, "index.ts")]) {
    if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) return candidate;
  }
  return base;
}

function loadTs(file) {
  const resolved = path.resolve(file);
  if (cache.has(resolved)) return cache.get(resolved).exports;
  if (resolved.endsWith(".json")) {
    const data = JSON.parse(fs.readFileSync(resolved, "utf8"));
    cache.set(resolved, { exports: data });
    return data;
  }
  const js = ts.transpileModule(fs.readFileSync(resolved, "utf8"), {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      esModuleInterop: true,
      resolveJsonModule: true,
    },
    fileName: resolved,
  }).outputText;
  const mod = { exports: {} };
  cache.set(resolved, mod);
  const dir = path.dirname(resolved);
  const req = (spec) => {
    const target = resolveSpec(spec, dir);
    return target ? loadTs(target) : require(spec);
  };
  new Function("require", "module", "exports", "__filename", "__dirname", js)(
    req, mod, mod.exports, resolved, dir,
  );
  return mod.exports;
}

const before = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, "utf8") : "";

/**
 * BUG-011 — the index is public, so it may not carry one line of a paid lesson
 * ("공개 파일에 유료 본문 0건"). The rule is the audit's (scripts/paidLeakCheck.mjs).
 * On a hit the previous file is put back, so a leaking index is never left on
 * disk to be committed, and the build stops.
 */
function refuseLeaks(written, restore) {
  const leak = findPaidLeaks(written);
  if (!leak.rows) return;
  fs.writeFileSync(OUT_FILE, restore);
  const sample = leak.hits.slice(0, 5).map((h) => `  ${h.course}/${h.id} ${h.kind}: ${h.text}`).join("\n");
  console.error(
    `public/search-index.json would publish paid lesson content: ${leak.rows} line(s) from ${leak.lessons} paid lesson(s) ${JSON.stringify(leak.byCourse)}\n${sample}\n` +
      "The previous file was restored. Remove the paid text from scripts/buildSearchIndex.ts — do not reorder it to get past this check.",
  );
  process.exit(1);
}

if (CHECK) {
  // Build into a scratch copy so --check never rewrites the committed file.
  const backup = before;
  loadTs(path.join(ROOT, "scripts", "buildSearchIndex.ts"));
  const after = fs.readFileSync(OUT_FILE, "utf8");
  refuseLeaks(after, backup);
  if (after !== backup) {
    fs.writeFileSync(OUT_FILE, backup);
    console.error("public/search-index.json is stale — run: node scripts/buildSearchIndex.mjs");
    process.exit(1);
  }
  console.log("public/search-index.json is current");
} else {
  loadTs(path.join(ROOT, "scripts", "buildSearchIndex.ts"));
  const after = fs.readFileSync(OUT_FILE, "utf8");
  refuseLeaks(after, before);
  const count = (text) => { try { return JSON.parse(text).length; } catch { return 0; } };
  // A build must never silently produce an empty or truncated index.
  if (count(after) < 500) throw new Error(`search-index.json has only ${count(after)} entries — the walk collected almost nothing`);
  console.log(
    before === after
      ? `public/search-index.json unchanged (${count(after)} entries)`
      : `public/search-index.json rebuilt: ${count(before)} → ${count(after)} entries`,
  );
}
